import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Web3 from "web3";
import { useCallback, useEffect, useState } from "react";

const Home: NextPage = () => {
  const [wallet, setWallet] = useState("");

  useEffect(() => {
    if (typeof window.ethereum !== "undefined") {
      console.log("MetaMask is installed!");
    }
  }, []);

  const onConnectClick = useCallback(async () => {
    // let web3 = new Web3(Web3.givenProvider);
    const acc = await window.ethereum.request({
      method: "eth_requestAccounts",
    });
    if (acc) {
      setWallet(acc[0]);
    }
    console.log("connected =>", wallet);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button
            className="p-4 bg-slate-600 text-white rounded-lg"
            onClick={() => onConnectClick()}
          >
            Connect wallet
          </button>
          <span className="text-slate-400 ml-2">{wallet}</span>
        </div>
      </main>
    </div>
  );
};

export default Home;
